### ISSUE TITLE
Error: Required named parameter 'parseErrorData' must be provided

### ISSUE THREAD

**Issue by MohammadDewji** [SimonWang9610/gpt_tokenizer#7] opened 2023-09-19 09:57 UTC
Hey Guys,

So, I tried using the package as follows 
` var AITokens = await Tokenizer().count(text!, modelName: "gpt-3.5-turbo");`

However, I keep getting this error as soon as I Import and try to run

`../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:218:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:243:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:263:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:287:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:311:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:331:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:351:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:372:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:392:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
`

**Comment by kendallsss** [comment] 2023-11-21 15:55
Same

**Comment by asgharas** [comment] 2023-11-28 14:24
same

**Comment by DiRuffy** [comment] 2023-12-16 18:19
same

**Comment by SimonWang9610** [comment] 2023-12-18 16:29
Please provide more details so that I can reproduce and fix it.
@zmyspc @asgharas @MohammadDewji

**Comment by MohammadDewji** [comment] 2023-12-19 22:07
Have included the stacktrace and line used for the error in the original comment... Do let me know if you need anything else. Seems like this is the error that is constantly being returned specifically in the FlutterRustBridgeTask at different lines... 
` Error: Required named parameter 'parseErrorData' must be provided....`

> Hey Guys,
> 
> So, I tried using the package as follows ` var AITokens = await Tokenizer().count(text!, modelName: "gpt-3.5-turbo");`
> 
> However, I keep getting this error as soon as I Import and try to run
> 
> `../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:218:57: Error: Required named parameter 'parseErrorData' must be provided. return _platform.executeNormal(FlutterRustBridgeTask( ^ ../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match. const FlutterRustBridgeTask({ ^^^^^^^^^^^^^^^^^^^^^ ../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:243:57: Error: Required named parameter 'parseErrorData' must be provided. return _platform.executeNormal(FlutterRustBridgeTask( ^ ../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match. const FlutterRustBridgeTask({ ^^^^^^^^^^^^^^^^^^^^^ ../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:263:57: Error: Required named parameter 'parseErrorData' must be provided. return _platform.executeNormal(FlutterRustBridgeTask( ^ ../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match. const FlutterRustBridgeTask({ ^^^^^^^^^^^^^^^^^^^^^ ../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:287:57: Error: Required named parameter 'parseErrorData' must be provided. return _platform.executeNormal(FlutterRustBridgeTask( ^ ../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match. const FlutterRustBridgeTask({ ^^^^^^^^^^^^^^^^^^^^^ ../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:311:57: Error: Required named parameter 'parseErrorData' must be provided. return _platform.executeNormal(FlutterRustBridgeTask( ^ ../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match. const FlutterRustBridgeTask({ ^^^^^^^^^^^^^^^^^^^^^ ../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:331:57: Error: Required named parameter 'parseErrorData' must be provided. return _platform.executeNormal(FlutterRustBridgeTask( ^ ../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match. const FlutterRustBridgeTask({ ^^^^^^^^^^^^^^^^^^^^^ ../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:351:57: Error: Required named parameter 'parseErrorData' must be provided. return _platform.executeNormal(FlutterRustBridgeTask( ^ ../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match. const FlutterRustBridgeTask({ ^^^^^^^^^^^^^^^^^^^^^ ../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:372:57: Error: Required named parameter 'parseErrorData' must be provided. return _platform.executeNormal(FlutterRustBridgeTask( ^ ../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match. const FlutterRustBridgeTask({ ^^^^^^^^^^^^^^^^^^^^^ ../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:392:57: Error: Required named parameter 'parseErrorData' must be provided. return _platform.executeNormal(FlutterRustBridgeTask( ^ ../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.0/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match. const FlutterRustBridgeTask({ ^^^^^^^^^^^^^^^^^^^^^ `

**Comment by SimonWang9610** [comment] 2023-12-19 22:20
@MohammadDewji Please provide the device model and Flutter version you used, so that I know how to diagnose this issue, as I could not reproduce it after trying on my iPhone, Pixel 6, Mac, and Windows.

**Comment by tolgaerdonmez** [comment] 2024-01-10 18:38
I've looked through the code and there seems to be a parameter missing in the generated code. I don't have any idea what's going on so couldn't solve it. Did you had time to look at ti? it would be very helpful.

**Comment by SimonWang9610** [comment] 2024-01-12 00:16
> I've looked through the code and there seems to be a parameter missing in the generated code. I don't have any idea what's going on so couldn't solve it. Did you had time to look at ti? it would be very helpful.

Thanks for your attention.

I cannot reproduce this issue on my machine, so I am not sure if it is related to the environment.

That would be great if you could provide your testing environment, like flutter version, Android/iOS version.

**Comment by samatzp** [comment] 2024-01-18 15:42
same: Error (Xcode): ../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:218:57: Error: Required named parameter 'parseErrorData' must be provided.

Iphone 14 pro max
MacBook Pro 16-inch, 2021 Apple M1 Max 32 GB

**Comment by masa8** [comment] 2024-02-07 17:29
Same

> ../../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:218:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(

Target: MacOS
Dev Env: MacBook Air,  Apple M1, OS: 14.3 (23D56)
Flutter 3.13.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12fccda598 (5 months ago) • 2023-09-19 13:56:11 -0700
Engine • revision bd986c5ed2
Tools • Dart 3.1.2 • DevTools 2.25.0

**Comment by masa8** [comment] 2024-02-07 19:00
There was PR  #8 for this issue.
I forked, applied this PR and using this temporal solution:

pubspec.yaml
```yaml
  flutter_gpt_tokenizer:
     git:
        url: https://github.com/masa8/gpt_tokenizer
        path: packages/flutter_gpt_tokenizer
        ref: main

**Comment by SimonWang9610** [comment] 2024-02-07 19:10
> Same
> 
> > ../../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:218:57: Error: Required named parameter 'parseErrorData' must be provided.
> > return _platform.executeNormal(FlutterRustBridgeTask(
> 
> Target: MacOS Dev Env: MacBook Air, Apple M1, OS: 14.3 (23D56) Flutter 3.13.5 • channel stable • https://github.com/flutter/flutter.git Framework • revision 12fccda598 (5 months ago) • 2023-09-19 13:56:11 -0700 Engine • revision bd986c5ed2 Tools • Dart 3.1.2 • DevTools 2.25.0

Have you tried the example? Is this issue reproducible for the example?

**Comment by SimonWang9610** [comment] 2024-02-07 19:29
This issue seems related to the version of flutter_rust_bridge, and I will upgrade it and re-generate the bridged dart code.

**Comment by masa8** [comment] 2024-02-07 19:47
> > Same
> > > ../../../.pub-cache/hosted/pub.dev/gpt_tokenizer-0.1.0/lib/src/gen/bridge_generated.dart:218:57: Error: Required named parameter 'parseErrorData' must be provided.
> > > return _platform.executeNormal(FlutterRustBridgeTask(
> > 
> > 
> > Target: MacOS Dev Env: MacBook Air, Apple M1, OS: 14.3 (23D56) Flutter 3.13.5 • channel stable • https://github.com/flutter/flutter.git Framework • revision 12fccda598 (5 months ago) • 2023-09-19 13:56:11 -0700 Engine • revision bd986c5ed2 Tools • Dart 3.1.2 • DevTools 2.25.0
> 
> Have you tried the example? Is this issue reproducible for the example?

I haven't tried the example though 
At least it works with the latest version, I think.
flutter_rust_bridge: ^1.82.6

Thank you for your quick response!!!

**Comment by SimonWang9610** [comment] 2024-02-07 20:50
I believe this issue can be fixed by https://github.com/SimonWang9610/gpt_tokenizer/pull/9.
The new version `v0.1.1` has been published, and feel free to reopen it if this issue still exists in the new version.

**Closed as completed by SimonWang9610** 2024-02-07 20:50 UTC
